<?php if (Mage::getStoreConfig('sm_slider/general/enable')): ?>
	<?php /*Zend_Debug::dump($this->getImages());die();*/ ?>
	<?php if ($this->getImages() !== false): ?>
	<div class="sm-slider">
		<div class="swiper-container">
			<div class="swiper-wrapper">
				<?php foreach ($this->getImages() as $image): ?>
				<div class="swiper-slide"> 
					<img src="<?php echo Mage::getUrl('media').$image->getPath() ?>" class="slide-image" alt="" />
					<?php if ($this->getSliderConfig('showtext')): ?>
					<div class="text-wrapper">
						<p class="text"><?php echo $image->getText(); ?></p>
					</div>	
					<?php endif; ?>
				</div>
				<?php endforeach ?>		
			</div>
		</div>
	 </div>
	<?php endif ?>
<?php endif; ?>
<style>
	.swiper-container {
		max-width: 1600px;
		width: 100%;
		/*max-height: 580px;*/
	}
	.sm-slider {
		/*margin-bottom: 10px;*/
	}
	/*.swiper-container, .sm-slider {height: 600px;}*/
	.slide-image {
		width: 100%;
		max-width: 1600px;
		/*height: 580px;*/
		/*overflow-y: hidden;*/
		/*height: 100%;*/
	}
	.swiper-slide .text-wrapper {
		position: relative;
	}
	.swiper-slide .text {
		position: absolute;
		bottom: -20px;
		right: 0;
		width: 100%;
		padding: 15px;
		text-align: right;
		background-color: rgba(99,99,99,0.5);
		color: #ddd;
	}
</style>

<script>
$j(function(){
  var mySwiper = new Swiper('.swiper-container',{
  	mode: '<?php echo $this->getSliderConfig("mode") ?>',
    loop: true,
    autoplay: 1000,
    speed: 3000,
  });
})
</script>