<div class="footer-container">
    <div class="footer">
    	<div class="container">
    		<?php echo $this->getChildHtml('footer.about-us') ?>
    		<?php echo $this->getChildHtml('footer.from-twitter') ?>
    		<?php echo $this->getChildHtml('footer.customer-service') ?>
    		<?php echo $this->getChildHtml('footer.connect-us') ?>
    	</div>
        <address class="copyright"><?php echo $this->getCopyright() ?></address>
    </div>
</div>
