<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<h2 class="subtitle"><?php echo $this->__('Featured product') ?></h2>
<div class="swiper-featured-container swiper-container">
    <div class="swiper-wrapper">
    <?php foreach ($_products->getItems() as $_product): ?>
            <div class="swiper-slide">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>" class="product-image">
                    <?php $_imgSize = 260; ?>
                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                </a>
                <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>"><?php echo $this->escapeHtml($_product->getName()) ?></a></h3>
                <?php echo $this->getPriceHtml($_product, true, '-new') ?>
            </div>
    <?php endforeach; ?>
    </div>
</div>
<?php endif; ?>
<?php echo $this->_getSwipperScript(); ?>
<style>
    .swiper-featured-container {}
    .swiper-featured-container .swiper-slide {
        width: 180px;/* margin-right: 20px;*/
    }
    .swiper-featured-container img {
        width: 100%; height: auto;
    }
</style>